### ISSUE TITLE
【PaddlePaddle Hackathon 2】91、新增random search超参数搜索api

### ISSUE THREAD

**Issue by TCChenlong** [tata1661/FSL-Mate#19]
（此 ISSUE 为 PaddlePaddle Hackathon 第二期活动的任务 ISSUE，更多详见 [【PaddlePaddle Hackathon 第二期】任务总览](https://github.com/PaddlePaddle/Paddle/issues/40234)）

【任务说明】

- 任务标题：新增random search超参数搜索api
- 模型技术标签：PaddlePaddle，hyperparameter optimization
- 任务难度：简单
- 详细描述：随机搜索即在搜索空间随机的搜索超参数。它是一种不需要优化问题梯度的数值优化方法，也是常用的基线超参数搜索算法。可参考NNI或HyperOpt，实现random search的超参数搜索api。

【提交内容】

- 设计文档，并提 PR 至 [PaddlePaddle/community](https://github.com/PaddlePaddle/community) 的 rfcs/FSL-Mate 目录
- 任务 PR 到 PaddleFSL
- 任务单测文件
- 调用路径：paddlefsl.hpo.rand

【合入标准】

在Omniglot和miniImageNet数据集的5-way 1-shot任务和5-way 5-shot任务进行测试。使MAML, ANIL, ProtoNet and RelationNet使用random search 搜索出的超参数能达到比原汇报结果更高的效果。

【技术要求】

熟练掌握 Python

【答疑交流】

- 如果在开发中对于上述任务有任何问题，欢迎在本 ISSUE 下留言交流。
- 对于开发中的共性问题，在活动过程中，会定期组织答疑，请大家关注官网&QQ群的通知，及时参与。

**Comment by jinyouzhi** [comment]
> 调用路径：paddle.hpo.rand
这个怎么理解，是要在Paddle框架中增加这个api，然后在本项目（FSL-Mate/PaddleFSL）中提供接口吗？还是开发在本项目（FSL-Mate/PaddleFSL）。

**Comment by tata1661** [comment]
> > 调用路径：paddle.hpo.rand
> 
> 这个怎么理解，是要在Paddle框架中增加这个api，然后在本项目（FSL-Mate/PaddleFSL）中提供接口吗？还是开发在本项目（FSL-Mate/PaddleFSL）。

是开发在本项目PaddleFSL中哈。多谢问询，任务描述已更正。
