### ISSUE TITLE
FSL——Mate

### ISSUE THREAD

**Issue by 30cuda77** [tata1661/FSL-Mate#21]
【队名】：青葱岁月夏小凡
【序号】：91
【状态】：报名
【链接】：https://github.com/tata1661/FSL-Mate/issues/19

**Comment by tata1661** [comment]
@30cuda77 Hi, 如任务页描述：
『若想要认领本次活动任务，请至 https://github.com/PaddlePaddle/Paddle/issues/40234 完成任务 ISSUE 认领。』
目前我在该页面没有看到你的信息，参赛请在该页面报名哈。
在这里开issue，飞桨的工作人员看不到的。
