### ISSUE TITLE
[Feature Request] refactor the project

### ISSUE THREAD

**Issue by wj-Mcat** [tata1661/FSL-Mate#24]
## Description

In the suggested [structuring python project](https://docs.python-guide.org/writing/structure/), there are some conventional structures & files & naming-style to make the project more readable and scalable.  And what's more, there are some github Action tools to run CI to lint & test code, run CD to publish the project.

##  Thought

I also maintain the project: [python-wechaty](https://github.com/wechaty/python-wechaty) and [paddle-prompt](https://github.com/wj-Mcat/paddle-prompt). So I'm familiar with the related opensource toolkits in python project.  I can create an another pr to complete this If you agree with it ? How do you think about it ? @tata1661

**Comment by tata1661** [comment]
@wj-Mcat It is nice to use CI tools with your help^^.  Thanks!
Just be careful if you consider different naming style which affects existing users. You can create a PR first. Then, we can discuss it.

**Comment by wj-Mcat** [comment]
I list the features and each one of them will match the one PR.

- [ ] re-structure the project with standard template
- [ ] create CI to lint & test the code
- [ ] create CD to auto-deploy the package to pypi 
- [ ] create docs with mkdoc tools and auto deployed to readthedocs website.

Let's make it on the way.

**Comment by wj-Mcat** [comment]
I'll create some prs which align with the above item to do accomplete the goals step by step on the dev branch.  We are welcome developers to contribute your own great ideas into this project.
