### ISSUE TITLE
ModuleNotFoundError: No module named 'pahelix'

### ISSUE THREAD

**Issue by JoanSF** [tata1661/FSL-Mate#25]
Install problem 1.1.0

File "/home/fangsifan/Few_Shot/FSL-Mate/PaddleFSL/paddlefsl/backbones/gin.py", line 17, in <module>
    from pahelix.model_zoo.pretrain_gnns_model import PretrainGNNModel

ModuleNotFoundError: No module named 'pahelix'

**Comment by mycccc0821** [comment]
Wow, I have the same problem here. May I ask you what operating system you used? Or just running in the AI studio?

**Comment by Phoenix0510** [comment]
I have the same problem. I have tried different platform, windows and Linux, both of them don't work at all.
![image](https://user-images.githubusercontent.com/16316893/163995101-2a8f2dbf-4d58-4231-b266-fa31fdb57870.png)

**Comment by mycccc0821** [comment]
> I have the same problem. I have tried different platform, windows and Linux, both of them don't work at all. ![image](https://user-images.githubusercontent.com/16316893/163995101-2a8f2dbf-4d58-4231-b266-fa31fdb57870.png)
Do you also have the problem after modifying the file in paddlefsl? I don't get an error when I don't modify the code at all, but I get an error when I try to call the paddlefsl after a custom modification.

**Comment by tata1661** [comment]
@Phoenix0510 @JoanSF @mycccc0821 , thanks for the interests in PaddleFSL. 
 To use GIN, you have to first install paddlehelix-1.0.1 or later versions. Please see README.md(https://github.com/tata1661/FSL-Mate/tree/master/PaddleFSL/examples/molecular_property_prediction#environment) for details.

**Comment by JoanSF** [comment]
@mycccc0821 @Phoenix0510 
install version 1.0.0，or install paddlehelix   according to @tata1661 answer

**Comment by wj-Mcat** [comment]
If I don't use the `gin` module, can I not install pahelix which increased the difficulty of the installation ?  If it support this feature, I think it will make the support more easier for beginner. 

***

This is my illusion: the package support different way to install

```shell
pip install paddlefsl

# this command will install gin included packages
pip install paddlefsl[bio]
```

***

also, there is way: checking the package at runtime which is not elegant but useful. 

How do you think about it ?

or

**Comment by Ren-Xin** [comment]
@JoanSF @businiaon @mycccc0821 @wj-Mcat 
`
export SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True
pip install rdkit-pypi
pip install pgl
pip install paddlehelix
`
