### ISSUE TITLE
[Feature Request] Meta Learner Based code 

### ISSUE THREAD

**Issue by wj-Mcat** [tata1661/FSL-Mate#28]
## Introduction

After https://github.com/tata1661/FSL-Mate/pull/23 merged, we can convert all of examples, under `examples/image_classification`, to meta learner based examples.  

I have an online meeting with @tata1661 before, and we believe that it will be more concise if the model-zoo examples be replaced with meta learner (optim-based) . Let's get it on the way.

**Comment by tata1661** [comment]
@wj-Mcat Nice work! Many thanks!
