### ISSUE TITLE
[Bug] Wrong head_position index in rc_position_embedding.py

### ISSUE THREAD

**Issue by King-Hell** [tata1661/FSL-Mate#31]
In [rc_position_embedding.py](https://github.com/tata1661/FSL-Mate/tree/master/PaddleFSL/paddlefsl/backbones/rc_position_embedding.py#L69) line 69:  
```
head_position_vector = paddle.to_tensor(rc_vector[:, :, -1], dtype='int64')
```
But in [rc_init_vector.py](https://github.com/tata1661/FSL-Mate/blob/master/PaddleFSL/paddlefsl/backbones/rc_init_vector.py#L208) line 208, the `head_position_idx` is -2 in `rc_embedding`.  
    
So I think it should be:
```
head_position_vector = paddle.to_tensor(rc_vector[:, :, -2], dtype='int64')
```

**Comment by tata1661** [comment]
Thanks! 
You are right. We now fix it.
