### ISSUE TITLE
Exception has occurred: ModuleNotFoundError，No module named 'paddle.nn'

### ISSUE THREAD

**Issue by chch2010523** [tata1661/FSL-Mate#34]
运行gnn的例子时，提示报错Exception has occurred: ModuleNotFoundError，No module named 'paddle.nn'
我的环境是 1080TI Ubuntu20.04
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Fri_Dec_17_18:16:03_PST_2021
Cuda compilation tools, release 11.6, V11.6.55
Build cuda_11.6.r11.6/compiler.30794723_0
NVIDIA-SMI 510.39.01 Driver Version: 510.39.01 CUDA Version: 11.6
在conda中安装了paddlepaddle-gpu版本2.3.1
paddle-bfloat 0.1.7 pypi_0 pypi
paddlehelix 1.0.1 pypi_0 pypi
paddlepaddle-gpu 2.3.1.post116 pypi_0 pypi
pandas 1.3.5 pypi_0 pypi
pgl 2.2.3.post0 pypi_0 pypi

**Comment by Ren-Xin** [comment]
@chch2010523 
这可能是paddle没有安装成功，可以测试一下以下代码是否可以运行
```
import paddle
print(paddle.__version__)
```
