### ISSUE TITLE
求教个问题

### ISSUE THREAD

**Issue by Salary-only-17k** [tata1661/FSL-Mate#38]
元学习不是说在识别A数据训练，学会识别B数据的能力吗？为什么代码中train、val、test数据用的是相同的数据？在实际测试中，我用猫狗数据集作为task-model的数据集，蜜蜂蚂蚁数据作为learn-model的数据集，效果并没有直接训练效果好。

**Comment by Ainavo** [comment]
我最近也在用FSL，方便加个好友探讨一下吗？qq:1811894192
