### ISSUE TITLE
您好，是否可以介绍下自定义的数据集如何实现训练评估等操作

### ISSUE THREAD

**Issue by lmqhello** [tata1661/FSL-Mate#41]
最好能够详细一些，非常感谢！

**Comment by lmqhello** [comment]
是否是
TRAIN_DATASET = paddlefsl.datasets.FC100(mode='train')
VALID_DATASET = paddlefsl.datasets.FC100(mode='valid')
TEST_DATASET = paddlefsl.datasets.FC100(mode='test')

把FC100修改成

**Comment by Ren-Xin** [comment]
@lmqhello 
是的，但是需要做一些小的修改，步骤如下：
1. 自定义一个数据预处理类，参照/paddlefsl/datasets下的方法：https://github.com/tata1661/FSLMate/tree/master/PaddleFSL/paddlefsl/datasets中的方法（如fc100中是通过file_name来指定FC数据集），如果是自定义数据集可以将文件校验部分改为pass
2.自定义一个训练类：参照examples中的方法，如（examples/image_classification/relationnet_image_classification.py, 将TRAIN_DATASET = paddlefsl.datasets.FC100换成自定义的数据预处理类

**Comment by tata1661** [comment]
@Ren-Xin  thanks~
