### ISSUE TITLE
安装步骤（dalao勿喷）

### ISSUE THREAD

**Issue by YiDanCheung** [tata1661/FSL-Mate#43]
conda create -n paddleFSL python=3.7 -y 
source activate paddleFSL 

安装GPU版的PaddlePaddle：python -m pip install paddlepaddle-gpu==2.4.2 -i https://pypi.tuna.tsinghua.edu.cn/simple
检查paddle是否安装成功：python -c "import paddle;print(paddle.utils.run_check());print(paddle.__version__)" 【出现提示信息：PaddlePaddle is installed successfully!】
再次验证：python -c "import paddle;print(paddle.ones([3,3]))" 	【如果GPU安装正确，输出就不会是0矩阵】

pip install rdkit-pypi
pip install pgl
pip install paddlehelix【若安装失败，Linux下设置环境变量 export SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True（Windows下用set），再次安装】
pip install paddlefsl

pip install scikit-learn
python -m pip install ujson

验证paddlefsl是否安装成功：python -c "import paddlefsl;print(paddlefsl.__version__)" 【输出：1.1.0】
安装过程结束。

**Comment by stoneken18** [comment]
这个paddlehelix有什么问题吗？我各种办法试过很多遍，在local, kaggle, Baidu AI Studio. 哪儿都装不上，结果paddlefsl看得挺好，我就是用不了，再不行只能回到pytroch了，怎么回事！！！？？？？

**Comment by tata1661** [comment]
> conda create -n paddleFSL python=3.7 -y source activate paddleFSL
> 
> 安装GPU版的PaddlePaddle：python -m pip install paddlepaddle-gpu==2.4.2 -i https://pypi.tuna.tsinghua.edu.cn/simple 检查paddle是否安装成功：python -c "import paddle;print(paddle.utils.run_check());print(paddle.**version**)" 【出现提示信息：PaddlePaddle is installed successfully!】 再次验证：python -c "import paddle;print(paddle.ones([3,3]))" 【如果GPU安装正确，输出就不会是0矩阵】
> 
> pip install rdkit-pypi pip install pgl pip install paddlehelix【若安装失败，Linux下设置环境变量 export SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True（Windows下用set），再次安装】 pip install paddlefsl
> 
> pip install scikit-learn python -m pip install ujson
> 
> 验证paddlefsl是否安装成功：python -c "import paddlefsl;print(paddlefsl.**version**)" 【输出：1.1.0】 安装过程结束。

@YiDanCheung  Thanks!

**Comment by tata1661** [comment]
> 这个paddlehelix有什么问题吗？我各种办法试过很多遍，在local, kaggle, Baidu AI Studio. 哪儿都装不上，结果paddlefsl看得挺好，我就是用不了，再不行只能回到pytroch了，怎么回事！！！？？？？

@stoneken18 我更新了installation guide，修正了错误指令，PaddleFSL的安装按照主页python setup.py install安装就可以。如果PaddleHelix安装有问题，可以查看它的官网https://github.com/PaddlePaddle/PaddleHelix/tree/v1.1.0，开issue。别担心，会有PaddleHelix技术同学回复你。

**Comment by stoneken18** [comment]
你好，谢谢你的回复，已经按照你的instruction试过装paddlehelix, 根本不行， 在问他们，paddlexhelix真是一垃圾！在自家的百度AI studio都装不上！！！！
