### ISSUE TITLE
文件使用路径问题

### ISSUE THREAD

**Issue by lish369sysu** [tata1661/FSL-Mate#45]
请教一下该如何修改root路径？也就是怎么使用当前文件夹下的raw_data文件夹？
同时example里面import的文件并不是当前路径下的，是~\anaconda3\envs\paddle_env\Lib\site-packages\paddlefsl-1.1.0-py3.8.egg\paddlefsl里面的文件，请问怎么修改使用当前文件夹下的py文件？

**Comment by YiDanCheung** [comment]
# Please edit env.sh to set the correct path of FSL-paddletoolkit directory.
# Then do:
source env.sh
# If you want to use our package frequently, you can add environment variables into .bashrc
cat env.sh >> ~/.bashrc
source ~/.bashrc

**Comment by lish369sysu** [comment]
> # Please edit env.sh to set the correct path of FSL-paddletoolkit directory.
> # Then do:
> source env.sh
> 
> # If you want to use our package frequently, you can add environment variables into .bashrc
> cat env.sh >> ~/.bashrc source ~/.bashrc

请问一下widows怎么操作哇？

**Comment by YiDanCheung** [comment]
你好，个人感觉这个仓库已经很久没有维护。版本没有跟着升，一直是1.0。后面使用的话可能要改很多代码。能力不济，已经放弃使用该库了
