### ISSUE TITLE
maml_image_classification训练报错：module 'paddlefsl.utils' has no attribute 'gradient_descent'

### ISSUE THREAD

**Issue by lish369sysu** [tata1661/FSL-Mate#46]
maml_image_classification训练报错：module 'paddlefsl.utils' has no attribute 'gradient_descent'
maml.py文件第61行utils.gradient_descent(model, inner_lr, loss_fn, approximate)
paddlefsl.utils目录下并没有gradient_descent.py
将gradient_descent改为manual_gradient_descent同样不可行

**Comment by tata1661** [comment]
now the problem is fixed.
